// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlRbOTFsncFKFfOlpPWNoYeDQLRe1YF24',
    appId: '1:1062287368090:web:8c51f90a134d9d59e66423',
    messagingSenderId: '1062287368090',
    projectId: 'quizcite',
    authDomain: 'quizcite.firebaseapp.com',
    storageBucket: 'quizcite.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvQPavy9A2dIVhy2CGGPK4KJ4Tpfwc15I',
    appId: '1:1062287368090:android:6b80a3f6929fc0fae66423',
    messagingSenderId: '1062287368090',
    projectId: 'quizcite',
    storageBucket: 'quizcite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLHYewzXSFSu5WkCygyJdM9o3e6VwSl8g',
    appId: '1:1062287368090:ios:7a1e962604e981afe66423',
    messagingSenderId: '1062287368090',
    projectId: 'quizcite',
    storageBucket: 'quizcite.firebasestorage.app',
    iosBundleId: 'com.example.quizCiteAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLHYewzXSFSu5WkCygyJdM9o3e6VwSl8g',
    appId: '1:1062287368090:ios:7a1e962604e981afe66423',
    messagingSenderId: '1062287368090',
    projectId: 'quizcite',
    storageBucket: 'quizcite.firebasestorage.app',
    iosBundleId: 'com.example.quizCiteAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlRbOTFsncFKFfOlpPWNoYeDQLRe1YF24',
    appId: '1:1062287368090:web:2c0afac1257f7d40e66423',
    messagingSenderId: '1062287368090',
    projectId: 'quizcite',
    authDomain: 'quizcite.firebaseapp.com',
    storageBucket: 'quizcite.firebasestorage.app',
  );
}
